-- MySQL Script generated by MySQL Workbench
-- Tue May 30 17:04:46 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema tasks
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `tasks` ;

-- -----------------------------------------------------
-- Schema tasks
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tasks` DEFAULT CHARACTER SET utf8mb3 ;
USE `tasks` ;

-- -----------------------------------------------------
-- Table `tasks`.`tasks`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tasks`.`tasks` ;

CREATE TABLE IF NOT EXISTS `tasks`.`tasks` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `uuid` VARCHAR(36) NOT NULL,
  `title` VARCHAR(50) NOT NULL,
  `description` VARCHAR(100) NOT NULL,
  `status` ENUM('PENDING', 'IN PROGRESS', 'DONE') NULL DEFAULT 'PENDING',
  `dueDate` TIMESTAMP(3) NULL DEFAULT NULL,
  `isPublic` TINYINT(1) NULL DEFAULT NULL,
  `createdBy` VARCHAR(36) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fkUser` (`createdBy` ASC) VISIBLE,
  INDEX `uuid` (`uuid` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `tasks`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tasks`.`users` ;

CREATE TABLE IF NOT EXISTS `tasks`.`users` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(40) NOT NULL,
  `email` VARCHAR(30) NOT NULL,
  `password` VARCHAR(70) NOT NULL,
  `userType` ENUM('Admin', 'User') NOT NULL DEFAULT 'User',
  `uuid` VARCHAR(36) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email` (`email` ASC) VISIBLE,
  INDEX `uuid` (`uuid` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 15
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `tasks`.`comments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tasks`.`comments` ;

CREATE TABLE IF NOT EXISTS `tasks`.`comments` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `uuid` VARCHAR(36) NOT NULL,
  `taskUUID` VARCHAR(36) NOT NULL,
  `userUUID` VARCHAR(36) NOT NULL,
  `comment` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `uuid` (`uuid` ASC) VISIBLE,
  INDEX `fkCommentUser` (`userUUID` ASC) VISIBLE,
  INDEX `fkCommentTask` (`taskUUID` ASC) VISIBLE,
  CONSTRAINT `fkCommentTask`
    FOREIGN KEY (`taskUUID`)
    REFERENCES `tasks`.`tasks` (`uuid`)
    ON DELETE CASCADE,
  CONSTRAINT `fkCommentUser`
    FOREIGN KEY (`userUUID`)
    REFERENCES `tasks`.`users` (`uuid`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 33
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `tasks`.`files`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tasks`.`files` ;

CREATE TABLE IF NOT EXISTS `tasks`.`files` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `uuid` VARCHAR(36) NOT NULL,
  `name` VARCHAR(10) NOT NULL,
  `format` VARCHAR(20) NOT NULL,
  `url` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `url` (`url` ASC) VISIBLE,
  INDEX `uuid` (`uuid` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `tasks`.`logbook`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tasks`.`logbook` ;

CREATE TABLE IF NOT EXISTS `tasks`.`logbook` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `uuid` VARCHAR(36) NOT NULL,
  `userUUID` VARCHAR(36) NOT NULL,
  `typeEvent` ENUM('Error', 'Success') NULL DEFAULT NULL,
  `event` VARCHAR(200) NOT NULL,
  `dateEvent` TIMESTAMP(3) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `uuid` (`uuid` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `tasks`.`tags`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tasks`.`tags` ;

CREATE TABLE IF NOT EXISTS `tasks`.`tags` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `uuid` VARCHAR(36) NOT NULL,
  `tag` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `tag` (`tag` ASC) VISIBLE,
  UNIQUE INDEX `uuid_2` (`uuid` ASC, `tag` ASC) VISIBLE,
  INDEX `uuid` (`uuid` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `tasks`.`taskfiles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tasks`.`taskfiles` ;

CREATE TABLE IF NOT EXISTS `tasks`.`taskfiles` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `uuid` VARCHAR(36) NOT NULL,
  `taskUUID` VARCHAR(36) NOT NULL,
  `fileUUID` VARCHAR(36) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `uuid` (`uuid` ASC) VISIBLE,
  INDEX `fkFileTask` (`fileUUID` ASC) VISIBLE,
  INDEX `fkTaskFile` (`taskUUID` ASC) VISIBLE,
  CONSTRAINT `fkFileTask`
    FOREIGN KEY (`fileUUID`)
    REFERENCES `tasks`.`files` (`uuid`)
    ON DELETE CASCADE,
  CONSTRAINT `fkTaskFile`
    FOREIGN KEY (`taskUUID`)
    REFERENCES `tasks`.`tasks` (`uuid`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `tasks`.`taskshared`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tasks`.`taskshared` ;

CREATE TABLE IF NOT EXISTS `tasks`.`taskshared` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `responsible` TINYINT(1) NULL DEFAULT '0',
  `uuid` VARCHAR(36) NOT NULL,
  `taskUUID` VARCHAR(36) NOT NULL,
  `userUUID` VARCHAR(36) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `taskUUID` (`taskUUID` ASC, `userUUID` ASC) VISIBLE,
  INDEX `uuid` (`uuid` ASC) VISIBLE,
  INDEX `fkUserTask` (`userUUID` ASC) VISIBLE,
  CONSTRAINT `fkTaskUser`
    FOREIGN KEY (`taskUUID`)
    REFERENCES `tasks`.`tasks` (`uuid`)
    ON DELETE CASCADE,
  CONSTRAINT `fkUserTask`
    FOREIGN KEY (`userUUID`)
    REFERENCES `tasks`.`users` (`uuid`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 22
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `tasks`.`tasktags`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tasks`.`tasktags` ;

CREATE TABLE IF NOT EXISTS `tasks`.`tasktags` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `uuid` VARCHAR(36) NOT NULL,
  `taskUUID` VARCHAR(36) NOT NULL,
  `tagUUID` VARCHAR(36) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `taskUUID` (`taskUUID` ASC, `tagUUID` ASC) VISIBLE,
  INDEX `uuid` (`uuid` ASC) VISIBLE,
  INDEX `fkTagTask` (`tagUUID` ASC) VISIBLE,
  CONSTRAINT `fkTagTask`
    FOREIGN KEY (`tagUUID`)
    REFERENCES `tasks`.`tags` (`uuid`)
    ON DELETE CASCADE,
  CONSTRAINT `fkTaskTag`
    FOREIGN KEY (`taskUUID`)
    REFERENCES `tasks`.`tasks` (`uuid`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 199
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `tasks`.`tokensvalid`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tasks`.`tokensvalid` ;

CREATE TABLE IF NOT EXISTS `tasks`.`tokensvalid` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `token` VARCHAR(225) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
